version: '3'

services:
  sgo:
    container_name: sgo
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    ports:
      - 3030:3030
    working_dir: /go/src
    volumes:
      - .:/go/src

  precommit:
    container_name: precommit
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: cp pre-commit .git/hooks/pre-commit
